baseURL = "https://zozo.sswin.site/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "SSWIN"                        # site title                     # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 5                           # shows the number of articles   # 首页显示文章数量
enableEmoji = true
disqusShortname = ""                   # your discuss shortname         # Disqus评论系统代码

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "Sswin"

[blackfriday]
  smartypants = true

[[menu.main]]                          # config your menu               # 配置菜单
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "链接"
  weight = 30
  identifier = "links"
  url = "https://blogroll.sswin.site/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "放进时光蛋里。"                                       # site's subTitle              # 网站二级标题
  footerSlogan = "享受当下。"                                   # site's footer slogan         # 网站页脚标语
  keywords = ["Hugo","theme","zozo"]                                   # site's keywords              # 网站关键字
  description = "Hugo theme zozo example site."                        # site's description           # 网站描述
  enableMathJax = true                                                 # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  Navbar = true
  Comments = true
  hugoEncryptorLanguage = "zh-cn"     # within ["zh-cn", "zh-cn"]
  googleAnalytics = "G-3XR6QD9MQ2"                   # your google analytics id       # Google统计代码
  
# waline.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://waline.js.org/guide/get-started.html
[params.waline]
  enable = false
  Url = "https://comment.sswin.xyz"
[params.gitalk]
  enable = false
  ClientSecret = "ed7ccda91c80d51e2bfd7e0b1dcbf52d9f0232cc"
[params.giscus]
  enable = true
  datarepo = "winsight/hugo_zozo_comment"


# Your socail's url
# 社交地址配置
[social]
  # github = ""
  # twitter = " "
  # facebook = " "
  # weibo = " "
  # instagram = " 1"
  Phone = "http://sms%3A%2F%2F18336983040"
  mail = "mailto://me@sswin.site"
  telegram = "//t.me/karl_s_bot"
  

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
